ACHGateway:
  Admin:
    BindAddress: ":9494"
  Inbound:
    HTTP:
      BindAddress: ":8484"
      # Transform:
      #   Encryption:
      #     AES:
      #       Key: "secret"
    Kafka:
      brokers:
        - "kafka1:9092"
      key: "admin"
      secret: "secret"
      group: "achgateway"
      tls: false
      topic: "ach.outgoing-files"
    ODFI:
      Interval: "1m"
      Processors:
        Corrections:
          Enabled: true
        Prenotes:
          Enabled: true
        Returns:
          Enabled: true
      ShardNames:
        - "testing"
      Storage:
        Directory: "./storage/"
        CleanupLocalDirectory: true
  Events:
    Stream:
      Kafka:
        Brokers:
          - "kafka1:9092"
        Key: admin
        Secret: secret
        TLS: false
        Topic: "ach.odfi-file-events"
    Transform:
      Encoding:
        Base64: true
  Sharding:
    Shards:
      - name: "testing"
        cutoffs:
          timezone: "America/Los_Angeles"
          windows:
            - "10:30"
            - "14:00"
        uploadAgent: "local-ftp"
        output:
          format: "nacha"
    Mappings:
      - shardKey: "foo"      # Could be random value (UUID, fixed string)
        shardName: "testing" # Maps to Sharding.Shards[_].name
    Default: "testing"
  Upload:
    agents:
      - id: "local-ftp"
        ftp:
          hostname: "ftp:2121"
          username: "admin"
          password: "123456"
        paths:
          inbound: "/inbound/"
          outbound: "/outbound/"
          reconciliation: "/reconciliation/"
          return: "/returned/"
    merging:
      directory: "./storage/"
      cleanup:
        enabled: false              # Set to true to enable automatic cleanup
        retentionDuration: "24h"    # Keep files for 24 hours after processing
        checkInterval: "1h"         # Check for files to clean up every hour
